<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugSymbols>False</DebugSymbols>
		<DebugType>None</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="FlowSynx.Plugins.Local.UnitTests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FlowSynx.PluginCore" Version="1.4.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <None Update="flowsynx.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="README.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
